name: Deploy to QA

on:
  workflow_run:
    workflows: ["Deploy to DEV"]
    types:
      - completed

jobs:
  Deploy_QA:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download deploy status artifact
        uses: actions/download-artifact@v3
        with:
          name: deploy-status
          path: deploy-status.txt
      - name: Check job statuses
        id: check_status
        run: |
          deploy_status=$(cat deploy-status.txt)
          echo "Deploy status: $deploy_status"

          if [[ "$deploy_status" == "skipped" ]]; then
            echo "Some jobs were skipped"
            exit 1
          else
            echo "No jobs were skipped"
          fi
      - name: Deploy QA
        if: success()
        steps: 
          - name: Deployment step
            run: echo "Deploying to qa..."
          - name: Health check step
            run: echo "Health check for QA..."
