name: Deploy to QA

on:
  workflow_run:
    workflows: ["Deploy to DEV"]
    types:
      - completed

jobs:
  Deploy_QA:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download deploy status artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-status
          path: ./artifact
      - name: Read deploy status
        id: read_status_1
        run: |
          cat ./artifact/deploy-status.txt
      - name: Download release status artifact
        uses: actions/download-artifact@v4
        with:
          name: release-status
          path: ./artifact
      - name: Read release status
        id: read_status_2
        run: |
          cat ./artifact/release-status.txt
      - name: Deployment step
        run: echo "Deploying to qa..."
      - name: Health check
        run: echo "Health check for QA..."
          
