name: Deploy to QA

on:
  workflow_run:
    workflows: ["Deploy to DEV"]
    types:
      - completed

jobs:
  Deploy_QA:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && startsWith(github.event.head_commit.message, 'release') 
    runs-on: ubuntu-latest
    steps:
      - name: Deployment step
        run: echo "Deploying to qa..."
      - name: Health check
        run: echo "Health check for QA..."
          
