name: Deploy to QA

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  validate-status:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download deploy status artifact
        run: |
          echo "Downloading release status artifact..."
          RELEASE_STATUS_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts" | \
          jq -r '.artifacts[] | select(.name == "release-status") | .archive_download_url')
          curl -sL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $RELEASE_STATUS_URL -o release-status.zip
          unzip release-status.zip -d release-status
      - name: Check artifact directories
        run: |
            ls -la release-status
      - name: Read release status
        id: read-status
        run: |
          if grep -q "true" release-status/release-status.txt; then
            echo "RELEASE_STATUS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_STATUS=false" >> $GITHUB_ENV
          fi
  Deploy_QA:
    needs: validate-status
    runs-on: ubuntu-latest
    if: env.RELEASE_STATUS == 'true'

    steps:
      - name: Deployment step
        run: echo "Deploying to qa..."
      - name: Health check
        run: echo "Health check for QA..."
